build:
   docker-compose build

build-nc:
   docker-compose build --no-cache

build-progress:
   docker-compose build --no-cache --progress=plain

down:
   docker-compose down --volumes

run:
   just down && docker-compose up

run-scaled:
   just down && docker-compose up --scale spark-worker=3

run-d:
   just down && docker-compose up -d

stop:
   docker-compose stop

submit:
   docker exec spark-master spark-submit --master spark://spark-master:7077 --deploy-mode client ./apps/$(app)
